// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
// eslint-config-prettier: disables formatting rules that would conflict with Prettier
// so that Prettier remains the single source of truth for code style (RULES.md §36).
const prettier = require('eslint-config-prettier');

module.exports = defineConfig([
  {
    // Vendored spartan-ng "helm" components (generated by @spartan-ng/cli). We own
    // the code but do not hold it to the app's conventions (tf- prefixes, etc.).
    ignores: ['src/app/ui/**'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
      prettier,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'tf',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'tf',
          style: 'kebab-case',
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
