import {
  lucideArchive,
  lucideArrowLeft,
  lucideCalendar,
  lucideCalendarDays,
  lucideCheck,
  lucideChevronDown,
  lucideChevronsUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleHelp,
  lucideCircleUserRound,
  lucideCircleX,
  lucideColumns3,
  lucideEllipsisVertical,
  lucideEqual,
  lucideFolder,
  lucideFolderOpen,
  lucideLayoutDashboard,
  lucideList,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMaximize2,
  lucideMessageSquare,
  lucideMinus,
  lucideMoon,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSettings,
  lucideShieldCheck,
  lucideSun,
  lucideTrash2,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideUserX,
  lucideX,
} from '@ng-icons/lucide';

/**
 * Every Lucide glyph the app renders, registered once and provided at the
 * application root (see app.config). Unlike Material's icon font, ng-icons
 * resolves `<ng-icon name="...">` against a registry, so an icon must be
 * listed here before any template can use it. Keyed by its Lucide export name.
 */
export const appIcons = {
  lucideArchive,
  lucideArrowLeft,
  lucideCalendar,
  lucideCalendarDays,
  lucideCheck,
  lucideChevronDown,
  lucideChevronsUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleHelp,
  lucideCircleUserRound,
  lucideCircleX,
  lucideColumns3,
  lucideEllipsisVertical,
  lucideEqual,
  lucideFolder,
  lucideFolderOpen,
  lucideLayoutDashboard,
  lucideList,
  lucideLoaderCircle,
  lucideLogOut,
  lucideMaximize2,
  lucideMessageSquare,
  lucideMinus,
  lucideMoon,
  lucidePencil,
  lucidePlus,
  lucideSearch,
  lucideSettings,
  lucideShieldCheck,
  lucideSun,
  lucideTrash2,
  lucideUser,
  lucideUserPlus,
  lucideUsers,
  lucideUserX,
  lucideX,
} as const;
